#!/bin/bash
# Comprehensive fepdf Test Suite (Robust version)
# Portions of this script were generated by Antigravity AI.

# We don't set -e because we want to see results for all files even if some fail.
# set -e

FEPDF="./target/release/fepdf"
RESULTS_DIR="fepdf_test/results"
mkdir -p "$RESULTS_DIR"

# Ensure binary exists
if [ ! -x "$FEPDF" ]; then
    echo "Error: fepdf binary not found at $FEPDF"
    exit 1
fi

echo "=== fepdf Verification Suite Starting ==="

# List of target files
FILES=$(find fepdf_test/ja fepdf_test/en -name "*.pdf")

TOTAL_TESTS=0
FAILED_TESTS=0

run_test() {
    local cmd_name=$1
    shift
    local log_file=$1
    shift
    echo -n "  [$cmd_name] "
    if "$@" > "$log_file" 2>&1; then
        echo "PASS"
    else
        echo "FAIL (Check $log_file)"
        FAILED_TESTS=$((FAILED_TESTS + 1))
    fi
    TOTAL_TESTS=$((TOTAL_TESTS + 1))
}

for FILE in $FILES; do
    BASENAME=$(basename "$FILE")
    FILE_RESULTS="$RESULTS_DIR/$BASENAME"
    mkdir -p "$FILE_RESULTS"

    echo "--- Testing: $BASENAME ---"

    # 1. info & audit
    run_test "info" "$FILE_RESULTS/info.txt" "$FEPDF" info "$FILE"
    run_test "audit" "$FILE_RESULTS/audit_internal.txt" "$FEPDF" info --audit "$FILE"

    # 2. upgrade
    run_test "upgrade" "$FILE_RESULTS/upgrade_log.txt" "$FEPDF" upgrade "$FILE" "$FILE_RESULTS/upgraded.v20.pdf"
    
    # 3. optimize
    run_test "optimize" "$FILE_RESULTS/optimize_log.txt" "$FEPDF" optimize "$FILE" "$FILE_RESULTS/optimized.pdf" --strip --vacuum

    # 4. repair
    run_test "repair" "$FILE_RESULTS/repair_log.txt" "$FEPDF" repair "$FILE" "$FILE_RESULTS/repaired.pdf"

    # 5. rotate
    run_test "rotate" "$FILE_RESULTS/rotate_log.txt" "$FEPDF" rotate -p 1 -a 90 "$FILE" "$FILE_RESULTS/rotated.pdf"

    # 6. split
    run_test "split" "$FILE_RESULTS/split_log.txt" "$FEPDF" split -o "$FILE_RESULTS/split.pdf" "$FILE"

    # 7. text
    run_test "text" "$FILE_RESULTS/text_log.txt" "$FEPDF" text -p 1 "$FILE"

    # 8. render
    # We treat render failure as a warning if not supported, but here we track it as a test.
    run_test "render" "$FILE_RESULTS/render_log.txt" "$FEPDF" render -p 1 "$FILE" "$FILE_RESULTS/render.png"

    # 9. External Audit (Arlington) for Upgraded File
    if [ -f "$FILE_RESULTS/upgraded.v20.pdf" ]; then
        run_test "external_audit" "$FILE_RESULTS/audit_external.txt" ./scripts/arlington_audit.sh "$FILE_RESULTS/upgraded.v20.pdf"
    else
        echo "  [external_audit] SKIP (Upgraded file missing)"
    fi

done

# 10. merge test
echo "--- Merge Test ---"
SAMPLE1=$(echo $FILES | awk '{print $1}')
SAMPLE2=$(echo $FILES | awk '{print $2}')
if [ -n "$SAMPLE1" ] && [ -n "$SAMPLE2" ]; then
    run_test "merge" "$RESULTS_DIR/merge_test_log.txt" "$FEPDF" merge -o "$RESULTS_DIR/merged.pdf" "$SAMPLE1" "$SAMPLE2"
fi

echo "=== fepdf Verification Suite Complete ==="
echo "Total Tests run: $TOTAL_TESTS"
echo "Total Failures: $FAILED_TESTS"
echo "Results are available in $RESULTS_DIR"

if [ $FAILED_TESTS -eq 0 ]; then
    exit 0
else
    exit 1
fi
